ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.reza.plugins.KoinKt.configureKoin
      - com.reza.plugins.DatabaseKt.configureDatabase
      - com.reza.plugins.SerializationKt.configureSerialization
      - com.reza.plugins.SecurityKt.configureSecurity
      - com.reza.plugins.RoutingKt.configureRouting

jwt:
  secret: "$JWT_SECRET:dev-secret-key-change-in-prod-do-not-use-in-production-123456"
  issuer: "$JWT_ISSUER:http://0.0.0.0:8080/"
  audience: "$JWT_AUDIENCE:http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"