ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.example.ApplicationKt.module ]
    }
}

jwt {
    # Looks for JWT_SECRET env var first; falls back to dev string if missing
    secret = "dev-secret-key-change-in-prod-do-not-use-in-production-123456"
    secret = ${?JWT_SECRET}

    issuer = "http://0.0.0.0:8080/"
    issuer = ${?JWT_ISSUER}

    audience = "http://0.0.0.0:8080/hello"
    audience = ${?JWT_AUDIENCE}

    realm = "Access to 'hello'"
}